language: node_js
sudo: required
services:
  - docker
node_js:
  - 10.15.1

env:
  global:
    - SHA=$(git rev-parse HEAD)

before_install:
  # Install kubectl
  - curl -O "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl
  - mkdir ${HOME}/.kube
  - cp kube.config ${HOME}/.kube/config
  - export PATH=$PATH:$HOME/.local/bin

  # Install awscli
  - pip install --user awscli
  - mkdir ${HOME}/.aws
  - echo "[default]"> ${HOME}/.aws/credentials
  - echo "region = ap-southeast-2">> ${HOME}/.aws/credentials
  - echo "output=json" >> ${HOME}/.aws/credentials

  # setup aws-iam-authenticator
  - curl -Lo aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.12.7/2019-03-27/bin/linux/amd64/aws-iam-authenticator
  - chmod +x aws-iam-authenticator
  - sudo mv ./aws-iam-authenticator /usr/local/bin
  - kubectl config unset clusters.kubernetes.certificate-authority-data
  - kubectl config set clusters.kubernetes.certificate-authority-data $KUBE_CLUSTER_CERTIFICATE

script:
  - echo "nothing"

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
